{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.2-plain.jar",
          "url": "jeju-onul-response-0.0.2-plain.jar",
          "size": 12859,
          "sha512": "54b46945d6d1c20faf6997c1873000e717b836ea820f36b8eb776e79e690e3ec635bb9bfaec65f7c3ec7b0a27427ebd62f711b5d05696f0ee980bc8e7246f3dd",
          "sha256": "47ec2d322f2c97b43df04fdc7ffc9f06f3c1ba65e2468372fc744dcb7fe56e00",
          "sha1": "9b044ded1599cf1a67c18d663bfc46a2bfbf5352",
          "md5": "49386c6c5002152b5338c512e8ac7a11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.2-plain.jar",
          "url": "jeju-onul-response-0.0.2-plain.jar",
          "size": 12859,
          "sha512": "54b46945d6d1c20faf6997c1873000e717b836ea820f36b8eb776e79e690e3ec635bb9bfaec65f7c3ec7b0a27427ebd62f711b5d05696f0ee980bc8e7246f3dd",
          "sha256": "47ec2d322f2c97b43df04fdc7ffc9f06f3c1ba65e2468372fc744dcb7fe56e00",
          "sha1": "9b044ded1599cf1a67c18d663bfc46a2bfbf5352",
          "md5": "49386c6c5002152b5338c512e8ac7a11"
        }
      ]
    }
  ]
}
