{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.1-plain.jar",
          "url": "wemeet-rest-docs-0.0.1-plain.jar",
          "size": 17047,
          "sha512": "f6fa0add9e93a81160b50d2b3b24c794e95d25864fc7614c1bad80ea83cb7e1f1978158c908ea8145a2d15cb554f727766e0860d9bdc2285a0d177ca74a02457",
          "sha256": "3ffc9978b3479f309db8c3b969515d5683ce236c023a9b5fec0f352a3773944c",
          "sha1": "7b967eec950829f239361280ba26142c8c46c91b",
          "md5": "c545a12344c0ab394b71b511c4fd881d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.1-plain.jar",
          "url": "wemeet-rest-docs-0.0.1-plain.jar",
          "size": 17047,
          "sha512": "f6fa0add9e93a81160b50d2b3b24c794e95d25864fc7614c1bad80ea83cb7e1f1978158c908ea8145a2d15cb554f727766e0860d9bdc2285a0d177ca74a02457",
          "sha256": "3ffc9978b3479f309db8c3b969515d5683ce236c023a9b5fec0f352a3773944c",
          "sha1": "7b967eec950829f239361280ba26142c8c46c91b",
          "md5": "c545a12344c0ab394b71b511c4fd881d"
        }
      ]
    }
  ]
}
