{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.1-plain.jar",
          "url": "wemeet-rest-docs-0.0.1-plain.jar",
          "size": 17047,
          "sha512": "065c8fbbc3f5ecc0f3e3a5f8bf576c1050e1f124df0fbe91848ee4e2433165be2df8e3d5ca59cc4cc473169b5307212bf3b28288a2a96708f3a63c6bdab0a534",
          "sha256": "2d3c78b187714ded5c92dc4de8e50d1401a05e504fd5a9d1ba4e614fd0659db9",
          "sha1": "fe57ad2ecbea4bcb14a057dcd4412bc20824dd6b",
          "md5": "d28ef184531320e559582dc441337476"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.1-plain.jar",
          "url": "wemeet-rest-docs-0.0.1-plain.jar",
          "size": 17047,
          "sha512": "065c8fbbc3f5ecc0f3e3a5f8bf576c1050e1f124df0fbe91848ee4e2433165be2df8e3d5ca59cc4cc473169b5307212bf3b28288a2a96708f3a63c6bdab0a534",
          "sha256": "2d3c78b187714ded5c92dc4de8e50d1401a05e504fd5a9d1ba4e614fd0659db9",
          "sha1": "fe57ad2ecbea4bcb14a057dcd4412bc20824dd6b",
          "md5": "d28ef184531320e559582dc441337476"
        }
      ]
    }
  ]
}
