{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-permission",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.3-plain.jar",
          "url": "jeju-onul-permission-0.0.3-plain.jar",
          "size": 6987,
          "sha512": "d54f6afe3fec29ae0d7885bcc34eae95b22397766f792e8707c951c1f2acefb4839244e79ad963c60d8fc44718bda9373bc0885fe43dcbeec4e9e8f00d974d64",
          "sha256": "ae027d36b87cbbdcee3473e2155b44942486dfa0c5821035200abb1191628fc3",
          "sha1": "719f00ced9eaca3e9af8540faeb59f7ba9e94509",
          "md5": "ff31e1dd2dab5a32311cb8522e447ca4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc"
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture-kotest",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.kotest.extensions",
          "module": "kotest-extensions-spring",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.3-plain.jar",
          "url": "jeju-onul-permission-0.0.3-plain.jar",
          "size": 6987,
          "sha512": "d54f6afe3fec29ae0d7885bcc34eae95b22397766f792e8707c951c1f2acefb4839244e79ad963c60d8fc44718bda9373bc0885fe43dcbeec4e9e8f00d974d64",
          "sha256": "ae027d36b87cbbdcee3473e2155b44942486dfa0c5821035200abb1191628fc3",
          "sha1": "719f00ced9eaca3e9af8540faeb59f7ba9e94509",
          "md5": "ff31e1dd2dab5a32311cb8522e447ca4"
        }
      ]
    }
  ]
}
