{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.7-plain.jar",
          "url": "wemeet-rest-docs-0.0.7-plain.jar",
          "size": 16348,
          "sha512": "19a758913b24820debc50cef8461ea133fa5d5b5ddf58cbc81f998ae9cb0d1811b0dff324471a8172e1f9f64e49d133dc2952cc5262d30a98f0c2838a0ec6898",
          "sha256": "7069d6d43c973a78d1c10f0030f273f1a440da392182ed59fc72bc25b45be916",
          "sha1": "95f0e9c44bf4e7d6a49e807c394a7ae55fe79b3d",
          "md5": "957a83e286c7a4685dde10b1b4062991"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.7-plain.jar",
          "url": "wemeet-rest-docs-0.0.7-plain.jar",
          "size": 16348,
          "sha512": "19a758913b24820debc50cef8461ea133fa5d5b5ddf58cbc81f998ae9cb0d1811b0dff324471a8172e1f9f64e49d133dc2952cc5262d30a98f0c2838a0ec6898",
          "sha256": "7069d6d43c973a78d1c10f0030f273f1a440da392182ed59fc72bc25b45be916",
          "sha1": "95f0e9c44bf4e7d6a49e807c394a7ae55fe79b3d",
          "md5": "957a83e286c7a4685dde10b1b4062991"
        }
      ]
    }
  ]
}
