{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "core-library",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-library-0.0.1-plain.jar",
          "url": "core-library-0.0.1-plain.jar",
          "size": 22710,
          "sha512": "b0e3508a791f1656d527a06c35e913cf5a631a3ab5b372dfedb986a26117af9bb52e2c33870281f60c7b9d84d852764b22d999b889b00e8354df505bb09a2d0f",
          "sha256": "be2a284c0447d432f29bbda7b2f9689da4f54b547256350d5b99bdd01b63e032",
          "sha1": "32880a418f6131a05ea87d4ba9ad84d9b4a26730",
          "md5": "ce0aa07e3736a4839d5913685c674254"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-library-0.0.1-plain.jar",
          "url": "core-library-0.0.1-plain.jar",
          "size": 22710,
          "sha512": "b0e3508a791f1656d527a06c35e913cf5a631a3ab5b372dfedb986a26117af9bb52e2c33870281f60c7b9d84d852764b22d999b889b00e8354df505bb09a2d0f",
          "sha256": "be2a284c0447d432f29bbda7b2f9689da4f54b547256350d5b99bdd01b63e032",
          "sha1": "32880a418f6131a05ea87d4ba9ad84d9b4a26730",
          "md5": "ce0aa07e3736a4839d5913685c674254"
        }
      ]
    }
  ]
}
