{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.8-plain.jar",
          "url": "jeju-onul-response-0.0.8-plain.jar",
          "size": 13039,
          "sha512": "86b20b3a27bca67821248d1cc7ccda3100691d881ab1669832fe7a4d8cb792c0ec0ab16e64993e727a9abe9ef741998074ee9ce6c1e8883e36c258e101b6c28f",
          "sha256": "e9637d42415d5097827affe1f106a60d2819f41d9bed350839feb0f42755d3a3",
          "sha1": "4b79de501e678208dba21964ae9458e174ca3b7a",
          "md5": "8ac6cfc7d81a07b791361673dac20e9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.8-plain.jar",
          "url": "jeju-onul-response-0.0.8-plain.jar",
          "size": 13039,
          "sha512": "86b20b3a27bca67821248d1cc7ccda3100691d881ab1669832fe7a4d8cb792c0ec0ab16e64993e727a9abe9ef741998074ee9ce6c1e8883e36c258e101b6c28f",
          "sha256": "e9637d42415d5097827affe1f106a60d2819f41d9bed350839feb0f42755d3a3",
          "sha1": "4b79de501e678208dba21964ae9458e174ca3b7a",
          "md5": "8ac6cfc7d81a07b791361673dac20e9a"
        }
      ]
    }
  ]
}
