{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.5-plain.jar",
          "url": "wemeet-rest-docs-0.0.5-plain.jar",
          "size": 16175,
          "sha512": "c32b7581429de587af4f3e1df5eeb3994538cf37a14ac855f6f7cf438fc782c36f87f7e54052750c1fab8b7f2b5dbdf10b1dfeb40f3e64254df1f105f66a1d24",
          "sha256": "8ad97d17ba3037833888e5ce7f47ef1a874036decece0cb93c85211ed0b41340",
          "sha1": "fa68a58ddb18284606856984c71ee6f0e8e0bf13",
          "md5": "b34e7a3c1235d9364beed9658b3a090f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.5-plain.jar",
          "url": "wemeet-rest-docs-0.0.5-plain.jar",
          "size": 16175,
          "sha512": "c32b7581429de587af4f3e1df5eeb3994538cf37a14ac855f6f7cf438fc782c36f87f7e54052750c1fab8b7f2b5dbdf10b1dfeb40f3e64254df1f105f66a1d24",
          "sha256": "8ad97d17ba3037833888e5ce7f47ef1a874036decece0cb93c85211ed0b41340",
          "sha1": "fa68a58ddb18284606856984c71ee6f0e8e0bf13",
          "md5": "b34e7a3c1235d9364beed9658b3a090f"
        }
      ]
    }
  ]
}
