{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.8-plain.jar",
          "url": "wemeet-rest-docs-0.0.8-plain.jar",
          "size": 16458,
          "sha512": "5493d5d030be905153d16e2143d5b69f24f14f087601fbf3f23eb8439eb099ead82d20fa815c1b3b2a6bda852098c82d6371e5cb0b89464b284dcd1d22eb2144",
          "sha256": "dddacebd663f41ad33f1cde5f68e2b7c38273fc61b74e3c7a1d79a53449a002a",
          "sha1": "1998dddcca567381dd9c7dc63edbbe432de184a1",
          "md5": "c637672d71fce3eb6a6b03471413f010"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.8-plain.jar",
          "url": "wemeet-rest-docs-0.0.8-plain.jar",
          "size": 16458,
          "sha512": "5493d5d030be905153d16e2143d5b69f24f14f087601fbf3f23eb8439eb099ead82d20fa815c1b3b2a6bda852098c82d6371e5cb0b89464b284dcd1d22eb2144",
          "sha256": "dddacebd663f41ad33f1cde5f68e2b7c38273fc61b74e3c7a1d79a53449a002a",
          "sha1": "1998dddcca567381dd9c7dc63edbbe432de184a1",
          "md5": "c637672d71fce3eb6a6b03471413f010"
        }
      ]
    }
  ]
}
