{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.2-plain.jar",
          "url": "wemeet-rest-docs-0.0.2-plain.jar",
          "size": 17019,
          "sha512": "3d8d9a9a92a17e3d982276bc286ef3af534dab1baebfd578a65326b4200015af00bf032841cc4c2aa612cc0364bc58ed6c7cf0b2c26f787bd01973168d5e22a9",
          "sha256": "bc7527378d5a9fcb06ace3e25af00cbca3a5158dfa009a65e87ae7c1fb72a21e",
          "sha1": "530e8d0a8db7e4db88d4da85e35ac52cd3bc6658",
          "md5": "d62fee9f55d7129c39cb5fd18b6ac407"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.2-plain.jar",
          "url": "wemeet-rest-docs-0.0.2-plain.jar",
          "size": 17019,
          "sha512": "3d8d9a9a92a17e3d982276bc286ef3af534dab1baebfd578a65326b4200015af00bf032841cc4c2aa612cc0364bc58ed6c7cf0b2c26f787bd01973168d5e22a9",
          "sha256": "bc7527378d5a9fcb06ace3e25af00cbca3a5158dfa009a65e87ae7c1fb72a21e",
          "sha1": "530e8d0a8db7e4db88d4da85e35ac52cd3bc6658",
          "md5": "d62fee9f55d7129c39cb5fd18b6ac407"
        }
      ]
    }
  ]
}
