{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.2-plain.jar",
          "url": "wemeet-rest-docs-0.0.2-plain.jar",
          "size": 17121,
          "sha512": "7304d1672a3f63f21ccf71a871ec1a1e2b5e8b6a1dd49f09158d9be5650426313b6b02937c4c684392bc48d32989ccb8ee0dae59830cbf7284dae5efa989b9e9",
          "sha256": "5a8b257dacf1499125c299ef262cdb053e483d1429937cd8e798917a6f811852",
          "sha1": "7fc406f92ec96e9ae3153a7253e5d6561b9d86c6",
          "md5": "6ebff2f14b36f334c65c68cc39962267"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.2-plain.jar",
          "url": "wemeet-rest-docs-0.0.2-plain.jar",
          "size": 17121,
          "sha512": "7304d1672a3f63f21ccf71a871ec1a1e2b5e8b6a1dd49f09158d9be5650426313b6b02937c4c684392bc48d32989ccb8ee0dae59830cbf7284dae5efa989b9e9",
          "sha256": "5a8b257dacf1499125c299ef262cdb053e483d1429937cd8e798917a6f811852",
          "sha1": "7fc406f92ec96e9ae3153a7253e5d6561b9d86c6",
          "md5": "6ebff2f14b36f334c65c68cc39962267"
        }
      ]
    }
  ]
}
