{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.9-plain.jar",
          "url": "jeju-onul-response-0.1.9-plain.jar",
          "size": 14329,
          "sha512": "bdbc9878427bfd0e33692565302a78d75792ba1fa772d00e3d0b7f7bb8672694f907911f2655d28187cc6fed0775ff9f7c53409d4e5d95454f603f59e03cbebb",
          "sha256": "8d52ea66000992f20769283e3e77615c2c068cd2d473d72c2713b8fd63bc10fd",
          "sha1": "be149291994b8ee98d5c199a51c8e39a4f75e2e4",
          "md5": "21c4ab0d2943e66b8df1c01e709ff1fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.9-plain.jar",
          "url": "jeju-onul-response-0.1.9-plain.jar",
          "size": 14329,
          "sha512": "bdbc9878427bfd0e33692565302a78d75792ba1fa772d00e3d0b7f7bb8672694f907911f2655d28187cc6fed0775ff9f7c53409d4e5d95454f603f59e03cbebb",
          "sha256": "8d52ea66000992f20769283e3e77615c2c068cd2d473d72c2713b8fd63bc10fd",
          "sha1": "be149291994b8ee98d5c199a51c8e39a4f75e2e4",
          "md5": "21c4ab0d2943e66b8df1c01e709ff1fc"
        }
      ]
    }
  ]
}
