{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.5-plain.jar",
          "url": "jeju-onul-response-0.0.5-plain.jar",
          "size": 12028,
          "sha512": "a111990d63085ad0944508415d26ad9a0574a162ff0cba03689d2e6abf18920578aea68d95036ab67b44045c20577391d7d746239854b4ad9fa74e701b492b17",
          "sha256": "05af7cafa1e41c2e796ffb76ef7bdc661d2a9979f33c7ab83dbaa857acbf0d5d",
          "sha1": "8822981a3dbb22aef5f23928f93eb5e2f657a675",
          "md5": "1bcf487b3b40b2019c618536fbce933b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.5-plain.jar",
          "url": "jeju-onul-response-0.0.5-plain.jar",
          "size": 12028,
          "sha512": "a111990d63085ad0944508415d26ad9a0574a162ff0cba03689d2e6abf18920578aea68d95036ab67b44045c20577391d7d746239854b4ad9fa74e701b492b17",
          "sha256": "05af7cafa1e41c2e796ffb76ef7bdc661d2a9979f33c7ab83dbaa857acbf0d5d",
          "sha1": "8822981a3dbb22aef5f23928f93eb5e2f657a675",
          "md5": "1bcf487b3b40b2019c618536fbce933b"
        }
      ]
    }
  ]
}
