{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.4-plain.jar",
          "url": "jeju-onul-response-0.0.4-plain.jar",
          "size": 12392,
          "sha512": "811037ab88fd233ac15b1a25673e730516d971d9a96b6c092ebf91ba89c77490e9f686bcd3bd3bb1383706be1c7aacbf79f0cb78eeb3a73da2658cbc9b0ce3ed",
          "sha256": "e8ef48edd0c9bf755fcd8226df02c4f1e0ce6c54c3846a0212b5bdb51445458b",
          "sha1": "d7e71c2d5005be5a9e2953522b181fc15ace1b89",
          "md5": "600ad3aadf1473928d443411b0756a03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.0.4-plain.jar",
          "url": "jeju-onul-response-0.0.4-plain.jar",
          "size": 12392,
          "sha512": "811037ab88fd233ac15b1a25673e730516d971d9a96b6c092ebf91ba89c77490e9f686bcd3bd3bb1383706be1c7aacbf79f0cb78eeb3a73da2658cbc9b0ce3ed",
          "sha256": "e8ef48edd0c9bf755fcd8226df02c4f1e0ce6c54c3846a0212b5bdb51445458b",
          "sha1": "d7e71c2d5005be5a9e2953522b181fc15ace1b89",
          "md5": "600ad3aadf1473928d443411b0756a03"
        }
      ]
    }
  ]
}
