{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.8-plain.jar",
          "url": "jeju-onul-response-0.1.8-plain.jar",
          "size": 14107,
          "sha512": "3871b9cffffb05b95c21061191a6c6345302f8c5e911566aa9f8c810b58335f124702bc11553d8e09e2d6dd088a5e23b7dcd3ef925b3acf6271363d32aeab23e",
          "sha256": "a858ac014e9c6740b0488498e59b8e6ba5210a8b7935e9cb5ff81dd1f2cd49a5",
          "sha1": "c50f4d60ca34171ae76101310f786a9036c48b22",
          "md5": "27b5cda9250025d3d27d20b21b45c316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.8-plain.jar",
          "url": "jeju-onul-response-0.1.8-plain.jar",
          "size": 14107,
          "sha512": "3871b9cffffb05b95c21061191a6c6345302f8c5e911566aa9f8c810b58335f124702bc11553d8e09e2d6dd088a5e23b7dcd3ef925b3acf6271363d32aeab23e",
          "sha256": "a858ac014e9c6740b0488498e59b8e6ba5210a8b7935e9cb5ff81dd1f2cd49a5",
          "sha1": "c50f4d60ca34171ae76101310f786a9036c48b22",
          "md5": "27b5cda9250025d3d27d20b21b45c316"
        }
      ]
    }
  ]
}
