{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.8-plain.jar",
          "url": "jeju-onul-response-0.1.8-plain.jar",
          "size": 14329,
          "sha512": "1999e3d4d3dc4c4bd62e24c3135a0c2c14ac31992139badd260dd256806a3966a80371ffcf17c33d47aab6d246144092475a67143d8e9c5acdc2eb476736b700",
          "sha256": "013eb2c38847f1241c2a3d949a7c790731a93b92f3320a61b995ec393051d5f2",
          "sha1": "9bdd1370b015d21de6c611e4e79c2bb98e6012af",
          "md5": "448d20d5767367131f290dbb3a854d60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.8-plain.jar",
          "url": "jeju-onul-response-0.1.8-plain.jar",
          "size": 14329,
          "sha512": "1999e3d4d3dc4c4bd62e24c3135a0c2c14ac31992139badd260dd256806a3966a80371ffcf17c33d47aab6d246144092475a67143d8e9c5acdc2eb476736b700",
          "sha256": "013eb2c38847f1241c2a3d949a7c790731a93b92f3320a61b995ec393051d5f2",
          "sha1": "9bdd1370b015d21de6c611e4e79c2bb98e6012af",
          "md5": "448d20d5767367131f290dbb3a854d60"
        }
      ]
    }
  ]
}
