{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "wemeet-rest-docs",
    "version": "0.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.9-plain.jar",
          "url": "wemeet-rest-docs-0.0.9-plain.jar",
          "size": 16612,
          "sha512": "70fe888f8861f4146c708c6505c0ab110df1056665a6a7bf5fd3bf469032e71f68a500874f4116cc09638cf30f82568b08c0d732394ec777686299d8d0dddf88",
          "sha256": "dd2247297e37876e3d877fc0a466118099f6b934c902865dbcd95d425e078d06",
          "sha1": "23082f9af6ff219f51c2342f0fcd68b2b05ec5f2",
          "md5": "d55060b351162a230048936e166fa954"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-test"
        },
        {
          "group": "org.springframework.restdocs",
          "module": "spring-restdocs-mockmvc"
        },
        {
          "group": "com.epages",
          "module": "restdocs-api-spec-mockmvc",
          "version": {
            "requires": "0.19.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "wemeet-rest-docs-0.0.9-plain.jar",
          "url": "wemeet-rest-docs-0.0.9-plain.jar",
          "size": 16612,
          "sha512": "70fe888f8861f4146c708c6505c0ab110df1056665a6a7bf5fd3bf469032e71f68a500874f4116cc09638cf30f82568b08c0d732394ec777686299d8d0dddf88",
          "sha256": "dd2247297e37876e3d877fc0a466118099f6b934c902865dbcd95d425e078d06",
          "sha1": "23082f9af6ff219f51c2342f0fcd68b2b05ec5f2",
          "md5": "d55060b351162a230048936e166fa954"
        }
      ]
    }
  ]
}
