{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "message-envelop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "url": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "size": 11358,
          "sha512": "30601a8eca82e63797bb9911d577a3228197cbf242ff2dda4be78bcf105442c9238695672c97371033a1059023032746adb431daeab11b02c952760babc9b5f0",
          "sha256": "a0f9360db212a030a362c00dc7170b3c503d6494f16a17abacf8aade895a1826",
          "sha1": "153e854ecd156b254dc3d3eed3260f8c8b369658",
          "md5": "c080f30a88a0f25a284e30f47223ae65"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.wemeet",
          "module": "domain-core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "url": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "size": 11358,
          "sha512": "30601a8eca82e63797bb9911d577a3228197cbf242ff2dda4be78bcf105442c9238695672c97371033a1059023032746adb431daeab11b02c952760babc9b5f0",
          "sha256": "a0f9360db212a030a362c00dc7170b3c503d6494f16a17abacf8aade895a1826",
          "sha1": "153e854ecd156b254dc3d3eed3260f8c8b369658",
          "md5": "c080f30a88a0f25a284e30f47223ae65"
        }
      ]
    }
  ]
}
