{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "message-envelop",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "url": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "size": 13269,
          "sha512": "e695e8f102dfcb2909f333ea9ec9188d51839133e20e93c90cffbcfd83c2af4fc095bc04a25e9aa6bbab57a12f66f73921924a4c8e973ce0364785c46c120bf8",
          "sha256": "1e40f1e7f9ace9d15fbfa26e9a155422c15ce85d5a16d23de21f4494fc9b2abf",
          "sha1": "f28882a2fc3f8d2a08dadb19b397d1cbc386cd9e",
          "md5": "bc4946887981026d1a00583fd0e713d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.wemeet",
          "module": "domain-core",
          "version": {
            "requires": "0.0.1-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "url": "message-envelop-0.0.1-SNAPSHOT-plain.jar",
          "size": 13269,
          "sha512": "e695e8f102dfcb2909f333ea9ec9188d51839133e20e93c90cffbcfd83c2af4fc095bc04a25e9aa6bbab57a12f66f73921924a4c8e973ce0364785c46c120bf8",
          "sha256": "1e40f1e7f9ace9d15fbfa26e9a155422c15ce85d5a16d23de21f4494fc9b2abf",
          "sha1": "f28882a2fc3f8d2a08dadb19b397d1cbc386cd9e",
          "md5": "bc4946887981026d1a00583fd0e713d7"
        }
      ]
    }
  ]
}
