{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "domain-core",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "domain-core-0.0.1-SNAPSHOT-plain.jar",
          "url": "domain-core-0.0.1-SNAPSHOT-plain.jar",
          "size": 12090,
          "sha512": "eb0030408bdd5c43525d6d0d88188345f09872acdc44cb9ba0cfd6721075798ee46b8eebce514105f36def0d1dc2b7036e6738272dd463094773a7c8b7811f74",
          "sha256": "70b5c47ca072c06496dcd2cd652c0a9c21cfebb8a65b78f46fe8df892b03a53a",
          "sha1": "a29ac5638620c1e73d0ff031aadca2c4a27619f8",
          "md5": "033f981146dde1aaf579fa822f5c3340"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "domain-core-0.0.1-SNAPSHOT-plain.jar",
          "url": "domain-core-0.0.1-SNAPSHOT-plain.jar",
          "size": 12090,
          "sha512": "eb0030408bdd5c43525d6d0d88188345f09872acdc44cb9ba0cfd6721075798ee46b8eebce514105f36def0d1dc2b7036e6738272dd463094773a7c8b7811f74",
          "sha256": "70b5c47ca072c06496dcd2cd652c0a9c21cfebb8a65b78f46fe8df892b03a53a",
          "sha1": "a29ac5638620c1e73d0ff031aadca2c4a27619f8",
          "md5": "033f981146dde1aaf579fa822f5c3340"
        }
      ]
    }
  ]
}
