{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-permission",
    "version": "0.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.5-plain.jar",
          "url": "jeju-onul-permission-0.0.5-plain.jar",
          "size": 9655,
          "sha512": "7ed624124ce087c180aa3811fed21a2d6f733e45b0e4218bea19ab07b9fb3bf24de5c654ec9b5e2825d38cda44ffe9ee021a723aeb0dc41cc29d3ca1e5c61005",
          "sha256": "11efae12d0ba44783ae29a78b8eea46aff52d62162edba8f8e95aa342e28e329",
          "sha1": "bb262c33442d2ef9eac8a73d04f1cd4f98501f05",
          "md5": "a665d5acffa31d953352c0790d64d610"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc"
        },
        {
          "group": "com.wemeet",
          "module": "jeju-onul-response",
          "version": {
            "requires": "0.1.2"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture-kotest",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.kotest.extensions",
          "module": "kotest-extensions-spring",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.5-plain.jar",
          "url": "jeju-onul-permission-0.0.5-plain.jar",
          "size": 9655,
          "sha512": "7ed624124ce087c180aa3811fed21a2d6f733e45b0e4218bea19ab07b9fb3bf24de5c654ec9b5e2825d38cda44ffe9ee021a723aeb0dc41cc29d3ca1e5c61005",
          "sha256": "11efae12d0ba44783ae29a78b8eea46aff52d62162edba8f8e95aa342e28e329",
          "sha1": "bb262c33442d2ef9eac8a73d04f1cd4f98501f05",
          "md5": "a665d5acffa31d953352c0790d64d610"
        }
      ]
    }
  ]
}
