{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-response",
    "version": "0.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.4-plain.jar",
          "url": "jeju-onul-response-0.1.4-plain.jar",
          "size": 13855,
          "sha512": "bf27c2bed28af64e0d0753968648c7b0140dec9677dc19243a06545a5b928784287d4ced643e6ca35342a07ed5aa1e644e5aaf9029da2232f12ecb9486fc90b4",
          "sha256": "d718859a1738e3c5b38d4a7996e449acc735d586a1360cf2d093582e71db8650",
          "sha1": "b76dd6cc79ad7fb0fac5cccf012de5658f0e45ca",
          "md5": "f7da39828d76817f09545ec08acca40b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-response-0.1.4-plain.jar",
          "url": "jeju-onul-response-0.1.4-plain.jar",
          "size": 13855,
          "sha512": "bf27c2bed28af64e0d0753968648c7b0140dec9677dc19243a06545a5b928784287d4ced643e6ca35342a07ed5aa1e644e5aaf9029da2232f12ecb9486fc90b4",
          "sha256": "d718859a1738e3c5b38d4a7996e449acc735d586a1360cf2d093582e71db8650",
          "sha1": "b76dd6cc79ad7fb0fac5cccf012de5658f0e45ca",
          "md5": "f7da39828d76817f09545ec08acca40b"
        }
      ]
    }
  ]
}
