{
  "formatVersion": "1.1",
  "component": {
    "group": "com.wemeet",
    "module": "jeju-onul-permission",
    "version": "0.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.6-plain.jar",
          "url": "jeju-onul-permission-0.0.6-plain.jar",
          "size": 9687,
          "sha512": "7bcc7011daacc324b297f93c725b61a088bca75797db28226969ae3817c56bd16db62c7809becfb44ddd95e5bc3070e7ced805743e1db871110fca0f18dd9a16",
          "sha256": "944d63884e5d496ad9536b39b0ea65cb6f6cf08a3efe106e52add494a15b7ad1",
          "sha1": "a38b26cd86dbdedae2a11c3f624423c8e934102a",
          "md5": "75a55cdc134b95b69b89cfa4416b827e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-webmvc"
        },
        {
          "group": "com.wemeet",
          "module": "jeju-onul-response",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.appmattus.fixture",
          "module": "fixture-kotest",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.kotest.extensions",
          "module": "kotest-extensions-spring",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "jeju-onul-permission-0.0.6-plain.jar",
          "url": "jeju-onul-permission-0.0.6-plain.jar",
          "size": 9687,
          "sha512": "7bcc7011daacc324b297f93c725b61a088bca75797db28226969ae3817c56bd16db62c7809becfb44ddd95e5bc3070e7ced805743e1db871110fca0f18dd9a16",
          "sha256": "944d63884e5d496ad9536b39b0ea65cb6f6cf08a3efe106e52add494a15b7ad1",
          "sha1": "a38b26cd86dbdedae2a11c3f624423c8e934102a",
          "md5": "75a55cdc134b95b69b89cfa4416b827e"
        }
      ]
    }
  ]
}
